apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: nodeserver
  newName: igooruh/pipeline-devops-warning
  newTag: 0424e4e2dedbc9d2c66f39a7531ca6550f877c0e
