apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: nodeserver
  newName: igooruh/pipeline-devops-warning
  newTag: 3619ade5b476335256218bdd21b4a8fdfb49db00
