apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: nodeserver
  newName: igooruh/pipeline-devops-warning
  newTag: a18333ad6f7eb5cc44ad526f87638aab42711e2a
