apiVersion: v1
kind: Service
metadata:
  namespace: pipeline-devops-warning
  name: pipeline-devops-warning-service
  labels:
    app: application-pipeline-devops-warning
    app.kubernetes.io/instance: bb-gitops-pipeline-devops
spec:
  selector:
    app: application-pipeline-devops-warning
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-8080